# Generated by Django 5.1.7 on 2025-03-18 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econtentapp', '0002_bibleandmanresources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BibleAndManResources',
            new_name='BibleAndManResource',
        ),
    ]
