# Generated by Django 5.1.7 on 2025-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econtentapp', '0003_rename_bibleandmanresources_bibleandmanresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleandmanresource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bible_and_man/images/'),
        ),
    ]
