# Generated by Django 5.1.7 on 2025-03-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econtentapp', '0007_alter_healthwellnessresource_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibleandmanresource',
            name='image',
        ),
        migrations.AddField(
            model_name='bibleandmanresource',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='bible_and_man_covers/'),
        ),
    ]
