# Generated by Django 5.1.7 on 2025-03-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econtentapp', '0008_remove_bibleandmanresource_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
