# Generated by Django 5.1.7 on 2025-03-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econtentapp', '0009_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Welcome to E-Content Platform!', max_length=255)),
                ('content', models.TextField(default='Dear Subscriber,\n\nThank you for joining our newsletter! You are now part of a growing community that enjoys exclusive access to valuable e-content, industry insights, and special updates.\n\n✨ What You’ll Get:\n✅ Latest updates on digital content and e-books  \n✅ Exclusive access to special offers and announcements  \n✅ Tips and resources to enhance your online experience  \n\nStay tuned for amazing content coming your way!  \n\nBest regards,  \nFidelity AfriTeam  \n')),
            ],
        ),
    ]
