# Generated by Django 5.1.7 on 2025-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econtentapp', '0010_newslettertemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(upload_to='ebooks/files/'),
        ),
        migrations.AlterField(
            model_name='onlinecourse',
            name='file',
            field=models.FileField(upload_to='online_courses/files/'),
        ),
    ]
